name: Build
on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile Firmware
    steps:
    - name: Hello world action step
      id: hello
      uses: interactionresearchstudio/YoYoMachines-FirmwareCompiler@v0.2
      with:
        repo-name: 'ESP32-SOCKETIO'
