name: Build
on: push
jobs:
  build:
    name: Build for ESP32
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      uses: ArminJo/arduino-test-compile@v2
      arduino-board-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
      platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
      required-libraries: Servo,Adafruit NeoPixel
