# This is the name of the workflow, visible on GitHub UI.
name: build

# Here we tell GitHub to run the workflow when a commit
# is pushed or a Pull Request is opened.
on: push

# This is the list of jobs that will be run concurrently.
# Since we use a build matrix, the actual number of jobs
# started depends on how many configurations the matrix
# will produce.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0

      - name: Install platform
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install libraries
        run: |
          arduino-cli lib install FastLED
          arduino-cli lib install WebSockets
          arduino-cli lib install ArduinoJson
          arduino-cli lib install AceButton

      - name: Checkout ESPAsyncWebServer
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncWebServer
          path: ESPAsyncWebServer

      - name: Checkout AsyncTCP
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          path: AsyncTCP

      - name: Checkout SocketIoClient
        uses: actions/checkout@v2
        with:
          repository: timum-viw/socket.io-client
          path: SocketIoClient

      - name: Move libs to Arduino directory
        run: |
          mv ESPAsyncWebServer Arduino/libraries/ESPAsyncWebServer
          mv AsyncTCP Arduino/libraries/AsyncTCP
          mv SocketIoClient Arduino/libraries/SocketIoClient

      - name: Name installed libraries
        run: arduino-cli lib list
